config/routes.rb
#   Copyright (c) 2011, Diaspora Inc.  This file is
#   licensed under the Affero General Public License version 3 or later.  See
#   the COPYRIGHT file.

Diaspora::Application.routes.draw do

  # Posting and Reading

  resources :reshares

  resources :aspects do
    put :toggle_contact_visibility
  end

  resources :status_messages, :only => [:new, :create]

  resources :posts, :only => [:show, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
    resources :comments, :only => [:create, :destroy, :index]
  end
  get 'p/:id' => 'posts#show', :as => 'short_post'

  # roll up likes into a nested resource above
  resources :comments, :only => [:create, :destroy] do
    resources :likes, :only => [:create, :destroy, :index]
  end


  get 'bookmarklet' => 'status_messages#bookmarklet'

  resources :photos, :except => [:index] do
    put :make_profile_photo
  end

  # ActivityStreams routes
  scope "/activity_streams", :module => "activity_streams", :as => "activity_streams" do
    resources :photos, :controller => "photos", :only => [:create]
  end

  resources :conversations do
    resources :messages, :only => [:create, :show]
    delete 'visibility' => 'conversation_visibilities#destroy'
  end

  resources :notifications, :only => [:index, :update] do
    get :read_all, :on => :collection
  end

  resources :tags, :only => [:index]
  scope "tags/:name" do
    post   "tag_followings" => "tag_followings#create", :as => 'tag_tag_followings'
    delete "tag_followings" => "tag_followings#destroy"
  end
  get 'tags/:name' => 'tags#show', :as => 'tag'

  resources :apps, :only => [:show]

  #Cubbies info page
  resource :token, :only => :show


  # Users and people

  resource :user, :only => [:edit, :update, :destroy], :shallow => true do
    get :export
    get :export_photos
  end

  controller :users do
    get 'public/:username'          => :public,          :as => 'users_public'
    match 'getting_started'         => :getting_started, :as => 'getting_started'
    get 'getting_started_completed' => :getting_started_completed
    get 'confirm_email/:token'      => :confirm_email,   :as => 'confirm_email'
  end

  # This is a hack to overide a route created by devise.
  # I couldn't find anything in devise to skip that route, see Bug #961
  match 'users/edit' => redirect('/user/edit')

  devise_for :users, :controllers => {:registrations => "registrations",
                                      :password      => "devise/passwords",
                                      :sessions      => "sessions",
                                      :invitations   => "invitations"} do
    get 'invitations/resend/:id' => 'invitations#resend', :as => 'invitation_resend'
    get 'invitations/email' => 'invitations#email', :as => 'invite_email'
  end

  get 'login' => redirect('/users/sign_in')

  scope 'admins', :controller => :admins do
    match :user_search
    get   :admin_inviter
    get   :stats, :as => 'pod_stats'
  end

  resource :profile, :only => [:edit, :update]

  resources :contacts,           :except => [:update, :create] do
    get :sharing, :on => :collection
  end
  resources :aspect_memberships, :only   => [:destroy, :create, :update]
  resources :post_visibilities,  :only   => [:update]

  get 'featured' => "contacts#featured", :as => 'featured_users'
  resources :people, :except => [:edit, :update] do
    resources :status_messages
    resources :photos
    get  :contacts
    get "aspect_membership_button" => :aspect_membership_dropdown, :as => "aspect_membership_button"
    collection do
      post 'by_handle' => :retrieve_remote, :as => 'person_by_handle'
      get :tag_index
    end
  end
  get '/u/:username' => 'people#show', :as => 'user_profile'


  # Federation

  controller :publics do
    get 'webfinger'             => :webfinger
    get 'hcard/users/:guid'     => :hcard
    get '.well-known/host-meta' => :host_meta
    post 'receive/users/:guid'  => :receive
    post 'receive/public'       => :receive_public
    get 'hub'                   => :hub
  end


  # External

  resources :authorizations, :only => [:index, :destroy]
  scope "/oauth", :controller => :authorizations, :as => "oauth" do
    get "authorize" => :new
    post "authorize" => :create
    post :token
  end

  resources :services, :only => [:index, :destroy]
  controller :services do
    scope "/auth", :as => "auth" do
      match ':provider/callback' => :create
      match :failure
    end
    scope 'services' do
      match 'inviter/:provider' => :inviter, :as => 'service_inviter'
      match 'finder/:provider'  => :finder,  :as => 'friend_finder'
    end
  end

  scope 'api/v0', :controller => :apis do
    get :me
  end


  # Mobile site

  get 'mobile/toggle', :to => 'home#toggle_mobile', :as => 'toggle_mobile'

  # Startpage

  root :to => 'home#show'
end

app/helpers/notifier_helper.rb
module NotifierHelper
  
  # @param post [Post] The post object.
  # @param opts [Hash] Optional hash.  Accepts :length and :process_newlines parameters.
  # @return [String] The truncated and formatted post.
  def post_message(post, opts={})
    opts[:length] ||= 200
    if post.respond_to? :formatted_message
      message = truncate(post.formatted_message(:plain_text => true), :length => opts[:length])
      message = process_newlines(message) if opts[:process_newlines]
      message
    else
      I18n.translate 'notifier.a_post_you_shared'
    end
  end

  # @param comment [Comment] The comment to process.
  # @param opts [Hash] Optional hash.  Accepts :length and :process_newlines parameters.
  # @return [String] The truncated and formatted comment.
  def comment_message(comment, opts={})
    opts[:length] ||= 600
    text = truncate(@comment.text, :length => opts[:length])
    text = process_newlines(text) if opts[:process_newlines]
    text
  end

  def invite_email_title
    names = @invites.collect{|x| x.sender.person.name}.uniq
    if @invites.empty? && names.empty?
      "Accept Your Diaspora* invite!"
    else
      "#{names.to_sentence} invited you to Diaspora*"
    end
  end
end

app/views/notifier/_notifier_css.haml
:css
  body{
    width:600px;
    font-family: 'Helvetica',sans-serif;
    }
  #container{
  }
  header{
    margin-bottom: 25px;
  }
  p{
    padding:5px;
  }
  p.small{
    font-size:smaller;
    color:#999;
    font-style:italic;
  }
  a{
    color:#107FC9;
    font-weight:bold;
  }
  a:hover{
    color: #22AAE0;
  }
  a:active{
    color: #005D9C;
  }

app/views/notifier/also_commented.text.haml
!= comment_message(@comment.text)

app/views/notifier/comment_on_post.html.haml
%p
  = comment_message(@comment.text, :process_newlines => true)
%p
  = link_to t('notifier.comment_on_post.reply', :name => @comment.post.author.name), post_url(@comment.post)

app/views/notifier/comment_on_post.text.haml
!= comment_message(@comment.text)

app/views/notifier/liked.text.haml
!= "#{t('notifier.liked.liked', :name => "#{@sender.name}")}:"
!=post_message(@like.target)

app/views/notifier/mentioned.html.haml
%p
  = post_message(@post, :process_newlines => true, :length => 600)
%p
  = link_to t('notifier.comment_on_post.reply', :name => @post.author.name), post_url(@post)

app/views/notifier/mentioned.text.haml
!= post_message(@post, :process_newlines => true, :length => 600)

app/views/notifier/private_message.html.haml
%p
  = post_message(@message, :process_newlines => true, :length => 2000)
%p
  = link_to t('.reply_to_or_view'), conversations_url(:conversation_id => @conversation)

app/views/notifier/private_message.text.haml
!= @message.text

app/views/notifier/reshared.text.haml
!= "#{t('notifier.reshared.reshared', :name => "#{@sender.name}")}:"
!=post_message(@reshare.root)

app/views/notifier/single_admin.html.haml
%p
  = t('notifier.hello', :name => @receiver.username)
%p
  = @string

  %br
  = t('notifier.thanks')
  = t('notifier.single_admin.admin')

app/views/notifier/single_admin.text.haml
!= t('notifier.hello', :name => @receiver.username)

!= @string

!= t('notifier.thanks')
!= t('notifier.single_admin.admin')

app/views/notifier/started_sharing.html.haml
%p
  = @sender.name
  = t('.sharing')
%p
  = link_to t('.view_profile', :name => @sender.first_name), person_url(@sender)

app/views/notifier/started_sharing.text.haml
!= "#{@sender.name}"
!= t('notifier.started_sharing.sharing')
!= t('.view_profile', :name => @sender.first_name)
!= person_url(@sender)